// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SubFinder.Data;
using System;

namespace SubFinder.Migrations
{
    [DbContext(typeof(SubFinderContext))]
    partial class SubFinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubFinder.Models.CustomRule", b =>
                {
                    b.Property<int>("CustomRuleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExecutionParameters");

                    b.Property<int>("ExecutionRule");

                    b.Property<string>("Unit");

                    b.HasKey("CustomRuleId");

                    b.ToTable("CustomRule");
                });

            modelBuilder.Entity("SubFinder.Models.Sentiment", b =>
                {
                    b.Property<int>("SentimentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ListId");

                    b.Property<int>("Polarity");

                    b.Property<double>("Strength");

                    b.Property<string>("Unit");

                    b.HasKey("SentimentId");

                    b.ToTable("Sentiment");
                });
#pragma warning restore 612, 618
        }
    }
}
